# Generated by Django 2.1.4 on 2019-05-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=6)),
                ('time', models.FloatField(default=0.0)),
                ('output', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunSubtaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('language', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('current_test', models.IntegerField(default=0)),
                ('is_invocation', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('sent_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Participant')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('problem_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.ProblemInfo')),
            ],
        ),
        migrations.AddField(
            model_name='runsubtaskinfo',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission'),
        ),
        migrations.AddField(
            model_name='runsubtaskinfo',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Subtask'),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission'),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Test'),
        ),
    ]
