# Generated by Django 2.1.4 on 2019-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='type',
            field=models.IntegerField(choices=[(0, 'ACM'), (1, 'IOI')], default=0),
        ),
    ]
