# Generated by Django 2.1.4 on 2019-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
