# Generated by Django 2.1.4 on 2019-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190330_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
