# Generated by Django 2.1.4 on 2019-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='br_number',
            field=models.IntegerField(default=0),
        ),
    ]
