# Generated by Django 2.1.4 on 2019-06-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_test_br_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='br_number',
            new_name='br_numberInput',
        ),
    ]
