# Generated by Django 2.1.4 on 2019-06-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20190608_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='br_numberOutput',
            field=models.IntegerField(default=0),
        ),
    ]
