# Generated by Django 2.1.4 on 2019-06-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_test_br_numberoutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='br_numberInput',
        ),
        migrations.RemoveField(
            model_name='test',
            name='br_numberOutput',
        ),
    ]
