# Generated by Django 2.1.4 on 2019-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20190330_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
