# Generated by Django 2.1.4 on 2019-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20190504_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
